### ISSUE TITLE
Hva skjer med ideene?

### ISSUE THREAD

**Issue by hfossli** [helsenorgelab/koronavirus#2]
Det hadde vært fint om README kunne sagt noe om 

- Hvem vurderer ideene? 
- Hva skjer videre om en idé er god? 
- Hvordan kan vi handle kjapt her?

**Comment by losolio** [comment]
Takk for spørsmålet! Ideene her vil være en av mange kilder for ulike arbeidsgrupper som jobber med de ulike delene av håndteringen av situasjonen, blant annet stabsmøtene. Vi tar kontakt dersom det er aktuelt å gå videre med en ide!

**Comment by hfossli** [comment]
Si fra om det går an å få 5-10 minutter så vi kan pitche det med egne ord!
