### ISSUE TITLE
Burde ikke repoet hete Covid-19?

### ISSUE THREAD

**Issue by haaakon** [helsenorgelab/koronavirus#3]
Best å bruke det offisielle navnet på et repo som omhandler det? Enklere å finne igjen på et senere tidspunkt også.

**Comment by losolio** [comment]
Det var mange kandidater coronavirus, SARS-CoV-2, Covid-19 og koronavirus. Vi jobber med innbyggere, og bruker stortsett koronavirus, men alle kunne vært valgt!
